### PR TITLE
Added geom_rect support for drawing rectangles

### PR DESCRIPTION
**Pull request by jhelvy**

### CODE REVIEW

**Comment by jhelvy** [comment]
I didn't mean to add the latest commit to this PR - I was just experimenting with a tabbed UI, putting the code to copy on a separate tab and rearranging a bit of the main annotation tab layout.

**Comment by MattCowgill** [comment]
hi @jhelvy this is good, thank you! I like the move of the plot size options to underneath the plot. Not 100% sure about the tabbed UI for code, but I agree it's probably better than what I had. I've been thinking about going with something similar to `esquisse:esquisser()` for that part of the UI.

**Comment by jhelvy** [comment]
Ooo esquisse:esquisser() is slick - very nice UI for exporting the code. I like the idea of having it as a pop-up rather than a separate tab.

**Comment by MattCowgill** [comment]
Thanks @jhelvy. There are a few things I want to tweak, but it won't let me push to `jhelvy/ggannotate` to update the PR, so I'll accept this and push to `master`.

**Pull request merged**
